### ISSUE TITLE
ModuleNotFoundError: xesmf

### ISSUE THREAD

**Issue by yvsathe14** [quishqa/AAS4WRF.py#7]
I followed the reame file to complete the installation. After running the script I am getting an error saying:
 ModuleNotFoundError: No module named 'xesmf'

However I can see all the required modules installed in conda list.

Could you please guide me?

@quishqa @alvv1986

**Comment by quishqa** [comment]
Hi @yvsathe14 ! 
Did you use the [Option A](https://github.com/quishqa/PyChEmiss#option-a) or [Option B](https://github.com/quishqa/PyChEmiss#option-b) for installation? 

Did you activate your environment before running?  (`conda activate PyChEmiss`)

**Comment by yvsathe14** [comment]
Hi @quishqa 
I used Option A and yes I did activate the environment before running.

**Comment by yvsathe14** [comment]
Hi @quishqa 
To update you, I re-tried using option B and now the script is running. I will explore and let you know the progress.

**Comment by yvsathe14** [comment]
Hi @quishqa
I am able to use the script now. But I have one query. I have emissions.txt for domain area with a coarse resolution i.e. 4 sq. km. I need to re-grid the 4 km data to 1 sq. km grid cell size WRF-Chem domain. Is it possible to use this script for my task?

**Comment by yvsathe14** [comment]
Hi @quishqa 
I am able to use the script now. But I have following queries:
1. Can we add emissions at a specific vertical level or height using this script? I could not find vertical dimension setting in the script.
2. The units if bith gaseous and aerosol species are set as "moles/km2/hour). The WRF-Chem requires emission units of aerosol species " ug/m2/s". How this is incorporated in the script.

**Comment by quishqa** [comment]
Hi,
I'm glad that option B works! 
1. The current version only works for surface emission. The [original version in ncl](https://github.com/alvv1986/AAS4WRF) has vertical level implementation. Check the files `namelis4D.emiss`and `AAS4WRFv1.4.ncl`
2. Yeah, that's true. All the species both gases and aerosol have the same units. Nevertheless, the script assumes that the values in the .txt file for gases are in mol/km2/hr and the aerossols in ug/m2/s.

Thanks for your comments, I'll try to correct these issues as soon as I can.

**Comment by yvsathe14** [comment]
Hi @quishqa ,
Thank you for your support.
I am closing this issue.
